# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories

version: 2
updates:
    - package-ecosystem: "github-actions"
      open-pull-requests-limit: 50
      directory: "/"
      labels:
          - "ðŸ¤– Dependencies"
      schedule:
          interval: "daily"
    - package-ecosystem: "gomod"
      open-pull-requests-limit: 50
      allow:
          # Allow both direct and indirect updates for all packages.
          - dependency-type: "all"
      directories:
          - "**/*"
      labels:
          - "ðŸ¤– Dependencies"
      schedule:
          interval: "daily"
      groups:
          fiber-modules:
              patterns:
                  - "github.com/gofiber/fiber/**"
          fasthttp-modules:
              patterns:
                  - "github.com/valyala/fasthttp"
                  - "github.com/valyala/fasthttp/**"
          golang-modules:
              patterns:
                  - "golang.org/x/**"
          opentelemetry-modules:
              patterns:
                  - "go.opentelemetry.io/**"
          fasthttp-websocket-modules:
              patterns:
                  - "github.com/fasthttp/websocket/**"
          valyala-utils-modules:
              patterns:
                  - "github.com/valyala/bytebufferpool"
                  - "github.com/valyala/tcplisten"
          mattn-modules:
              patterns:
                  - "github.com/mattn/go-colorable"
                  - "github.com/mattn/go-isatty"
                  - "github.com/mattn/go-runewidth"
          shirou-modules:
              patterns:
                  - "github.com/shirou/gopsutil"
                  - "github.com/shirou/gopsutil/**"
          ebitengine-modules:
              patterns:
                  - "github.com/ebitengine/**"
          klauspost-modules:
              patterns:
                  - "github.com/klauspost/**"
          tklauser-modules:
              patterns:
                  - "github.com/tklauser/**"
          google-modules:
              patterns:
                  - "github.com/google/**"
                  - "google.golang.org/**"
          testing-modules:
              patterns:
                  - "github.com/stretchr/**"
                  - "github.com/davecgh/go-spew"
                  - "github.com/pmezard/go-difflib"
          openapi-modules:
              patterns:
                  - "github.com/go-openapi/**"
          yaml-modules:
              patterns:
                  - "gopkg.in/yaml.*"
