# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    -   package-ecosystem: "gomod"
        directory: "/paseto/" # Location of package manifests
        labels:
            - " Dependencies"
        schedule:
            interval: "daily"
    -   package-ecosystem: "gomod"
        directory: "/fiberzap/" # Location of package manifests
        labels:
            - " Dependencies"
        schedule:
            interval: "daily"
    -   package-ecosystem: "gomod"
        directory: "/otelfiber/" # Location of package manifests
        labels:
            - " Dependencies"
        schedule:
            interval: "daily"
    -   package-ecosystem: "gomod"
        directory: "/otelfiber/example/" # Location of package manifests
        labels:
            - " Dependencies"
        schedule:
            interval: "daily"
    -   package-ecosystem: "gomod"
        directory: "/swagger/" # Location of package manifests
        labels:
            - " Dependencies"
        schedule:
            interval: "daily"
    -   package-ecosystem: "gomod"
        directory: "/casbin/" # Location of package manifests
        labels:
            - " Dependencies"
        schedule:
            interval: "daily"
    -   package-ecosystem: "gomod"
        directory: "/fibernewrelic/" # Location of package manifests
        labels:
            - " Dependencies"
        schedule:
            interval: "daily"
